service: musikaar-test

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  memorySize: 128
  timeout: 3
  
plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  allowedHeaders:
    - Accept
    - Content-Type
    - Content-Length
    - Authorization
  stage: ${opt:stage, self:provider.stage}

functions:
  create-student:
    handler: api/v1/create-student.handler
    description: POST /api/v1/students
    events:
      - http:
          path: api/v1/students
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  get-students:
    handler: api/v1/get-students.handler
    description: GET /api/v1/students
    events:
      - http:
          path: api/v1/students
          method: get
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}  

  get-student:
    handler: api/v1/get-student.handler
    description: GET /api/v1/students/{studentId}
    events:
      - http:
          path: api/v1/students/{studentId}
          method: get
          request:
            parameters:
              paths:
                studentId: true
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  update-student:
    handler: api/v1/update-student.handler
    description: PUT /api/v1/students/{studentId}
    events:
      - http:
          path: api/v1/students/{studentId}
          method: put
          request:
            parameters:
              paths:
                studentId: true
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  delete-student:
    handler: api/v1/delete-student.handler
    description: DELETE /api/v1/students/{studentId}
    events:
      - http:
          path: api/v1/students/{studentId}
          method: delete
          request:
            parameters:
              paths:
                studentId: true
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}